ALTER TABLE T_BID DROP CONSTRAINT T_BID_BID_ITEM_ID
ALTER TABLE T_BID DROP CONSTRAINT T_BID_BID_BIDDER
ALTER TABLE T_USER_PICTURE DROP CONSTRAINT TUSERPICTUREUSERID
ALTER TABLE T_ITEM DROP CONSTRAINT T_ITEM_SELLER_ID
ALTER TABLE T_ORDER DROP CONSTRAINT TORDERITEM_ITEM_ID
ALTER TABLE T_ORDER DROP CONSTRAINT TORDERUSER_USER_ID
ALTER TABLE T_ORDER DROP CONSTRAINT TRDRBLLNGNFBLLNGID
ALTER TABLE T_ORDER DROP CONSTRAINT TRDSHPPNGNFSHPPNGD
ALTER TABLE T_USER_GROUP DROP CONSTRAINT TUSER_GROUPUSER_ID
ALTER TABLE T_USER_GROUP DROP CONSTRAINT TUSERGROUPGROUP_ID
DROP TABLE T_BID
DROP TABLE T_USER
DROP TABLE T_USER_PICTURE
DROP TABLE T_BILLING_DETAILS
DROP TABLE T_ITEM
DROP TABLE T_ORDER
DROP TABLE T_SHIPPING_DETAILS
DROP TABLE T_GROUP
DROP TABLE T_USER_GROUP
DELETE FROM SEQUENCE WHERE SEQ_NAME = 'SEQ_GEN'
DROP SEQUENCE BID_SEQUENCE RESTRICT
